services:
  app:
    image: ghcr.io/thierryte/spring-ai-rag-frontend:latest
    container_name: ai-rag-frontend
    restart: unless-stopped
    env_file: .env
    ports:
      - "${FRONTEND_PORT:-8081}:80"
    networks:
      - default
      - spring-ai-rag_default

networks:
  spring-ai-rag_default:
    external: true
